spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      file-size-threshold: 0
      max-file-size: 1MB
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

  application:
    name: bookkeepings
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bookkeeping
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
knife4j:
  enable: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.bookkeeping.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      update-strategy: not_null
      id-type: assign_id
aliyun :
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: javazou
    region : cn-beijing



